### ISSUE TITLE
load_gs requires write permissions, even with h5_readonly = TRUE

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/cytolib#36]
This was discovered by internal tests that were failing due to symlinking to test file directories for which I did not have write permissions (even though that shouldn't be necessary), but it was fortunate as it exposed the underlying problem that `load_gs` requires write permissions for the H5 files of the archive, even when `h5_readonly` is set to `TRUE`.

To reproduce, block write permissions for the H5 file of a `GatingSet` archive directory to the user owning the R session. I used `gs_manual` from `flowWorkspaceData` and blocked write permissions.

```
$ sudo chmod -R 555 gs_manual/
$ ls -l gs_manual
total 5892
-r-xr-xr-x 1 jpwagner g_jpwagner      89 Apr  5 12:23 63c60e66-779b-4712-ad6e-b9349b965401.gs
-r-xr-xr-x 1 jpwagner g_jpwagner 5778880 Apr  5 12:23 CytoTrol_CytoTrol_1.fcs.h5
-r-xr-xr-x 1 jpwagner g_jpwagner  247118 Apr  5 12:23 CytoTrol_CytoTrol_1.fcs.pb
```
Then, in `R`:
```
# h5_readonly = TRUE is default anyway
> load_gs("gs_manual", h5_readonly = TRUE)
     error #000: in H5Fopen(): line 509
        major: File accessibilty
        minor: Unable to open file
     error #001: in H5F_open(): line 1498
        major: File accessibilty
        minor: Unable to open file
     error #002: in H5FD_open(): line 734
        major: Virtual File Layer
        minor: Unable to initialize object
     error #003: in H5FD_sec2_open(): line 346
        major: File accessibilty
        minor: Unable to open file
 Error in .cpp_loadGatingSet(normalizePath(path), h5_readonly, select.sn,  : 
  hdf Error 
```

A rough stack trace:
`load_gs` --> `.cpp_loadGatingSet` --> `load_gatingset`
https://github.com/RGLab/flowWorkspace/blob/4b30a5baeacf62ad902d08c832d3a149912a5dd1/src/R_GatingSet.cpp#L224
-->`add_GatingHierarchy`
https://github.com/RGLab/cytolib/blob/a009aa8d18c549e6b5ab8a61c5d61ff5bfee619a/inst/include/cytolib/GatingSet.hpp#L251
-->`H5CytoFrame` constructor
https://github.com/RGLab/cytolib/blob/a009aa8d18c549e6b5ab8a61c5d61ff5bfee619a/src/GatingHierarchy.cpp#L344
Which, although it initializes the `readonly_` flag appropriately for the new `H5CytoFrame`, still has the issue of opening the file with the default file access flag, 
https://github.com/RGLab/cytolib/blob/d270e923d671fc875d5500a4aea595e6767a2e5a/src/H5CytoFrame.cpp#L130-L133
which is read/write:
https://github.com/RGLab/cytolib/blob/a009aa8d18c549e6b5ab8a61c5d61ff5bfee619a/inst/include/cytolib/H5CytoFrame.hpp#L35

This may be as simple as temporarily overriding the `default_flag` for `H5File`  with `H5F_ACC_RDONLY` if the `readonly` flag passed down is TRUE, but that likely has wider implications.

**Comment by mikejiang** [comment]
>but that likely has wider implications.

You are right . There was reason for this `default_flags` to be const, which was breifly explaned here https://github.com/RGLab/cytolib/blob/a009aa8d18c549e6b5ab8a61c5d61ff5bfee619a/inst/include/cytolib/H5CytoFrame.hpp#L28
We need to think more carefully about the solution to this permission issue

**Comment by mikejiang** [comment]
The current implementation is related to the concern of multi-opens of the same h5 file discussed in #15 
Basically we always set the h5 flag to `H5F_ACC_RDWR` to avoid the conflicting `facl` among multiple openers.  e.g. a second `openFile` call  with `H5F_ACC_RDONLY` will simply automatically inherit the previous `H5F_ACC_RDWR` flag from previous opener regardless, thus cause the confusion or unexpected data tampering.

However, since we decided to no longer maintain the state of h5 file handler which means every `H5CytoFrame` API call will immediately close the file once finished. Therefore we essentially rule out the possibility of multi-openers case (unless APIs are invoked concurrently through multi-thread, but that parallel typically runs at sample-wise, rarely needs to do concurrent IO on the same file, also concurrent callers are typically from the same process ,thus won't  face the conflicting permission flags anyway).

So we can safely change h5 flag according to the `readonly` argument from the user.
